# GitHub Actions
name: GitHubActions

env:
  APPLICATION_NAME: "MyApp"
  DEPLOY_PACKAGE_NAME: "myApp-deploy-ver-${{github.sha}}"

on:
  push:
    branches: 
      master
jobs: 
  my-build:
    runs-on: ubuntu-latest
    steps:
    - name: Print msg
      run: echo "Hello Lena from build job!"
    
    - name: Execute few commands
      run: |
        echo "Hello msg1"
        echo "Hello msg2"
        echo "Hello msg3"
        echo "App name ${{env.APPLICATION_NAME}}"
        
    - name: List current folder
      run: ls -la
        
    - name: Git clone my repo
      run: actions/checkout@v3.3.0
        
    - name: List current folder
      run: ls -la
    
    
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-build]
    
    steps:
    - name: Print msg
      run: echo "Hello Lena from deploy job!"
      
    - name: Deploy package
      run: |
        echo "Deploy msg4"
        echo "Deploy msg5"
        echo "Deploy msg6"
        echo "Deploy name ${{env.DEPLOY_PACKAGE_NAME}}"
    
    - name: Check if there is a aws
      run: aws --version
      
    - name: Check if there is a zip
      run: zip
