# GitHub Actions
name: CI-CD-Pipeline-to-AWS-ElasticBeanStalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "crm-business-bucket"
  EB_APPLICATION_NAME: "crm-business"
  EB_ENVIRONMENT_NAME: "crm-business-env"
  DEPLOY_PACKAGE_NAME: "crm-business-${{github.sha}}.zip"
  AWS_REGION_NAME: "us-west-2"
  
  

on:
  push:
    branches: 
      master
jobs: 
  my-ci-part:
    runs-on: ubuntu-latest
    steps:
    - name: Clone our repo
      uses: actions/checkout@v3.3.0
      
    - name: Create zip deployment package
      run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
      
  
      
      
    
   
  
